language: java

sudo: false

git:
  depth: false

jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: swce

script:
  - sonar-scanner

install:
  - ./gradlew clean build jacocoTestReport coveralls

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_COMMIT_MESSAGE" == "*[Release]*" ]; then ./gradlew bintrayUpload; else echo "Skipping release"; fi

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache

notifications:
  email:
    - lchayoun@gmail.com
