language: java

sudo: false

jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "SWCE_spring-cloud-zuul-ratelimit"

script:
  - sonar-scanner

install:
  - ./gradlew build sonarqube

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache

notifications:
  email:
    - lchayoun@gmail.com
