language: java

sudo: false

jdk:
  - openjdk8

install:
  - ./gradlew build

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache

notifications:
  email:
    - lchayoun@gmail.com
